baseURL: https://amohamed.io/
buildDrafts: false
buildExpired: false
buildFuture: false
enableInlineShortcodes: true
enableRobotsTXT: true
menu:
  main:
    - name: archive
      url: archive
      weight: 5
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
minify:
  disableXML: true
  minifyOutput: true
paginate: 5
params:
  ShowReadingTime: true
  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
  author: 'Anas Mohamed'
  comments: false
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  defaultTheme: auto
  description: 'things & stuff'
  disableSpecial1stPost: false
  disableThemeToggle: false
  env: production
  fuseOpts:
    distance: 1000
    isCaseSensitive: false
    keys:
      - title
      - permalink
      - summary
      - content
    location: 0
    minMatchCharLength: 0
    shouldSort: true
    threshold: 0.4
  hidemeta: false
  homeInfoParams:
    Content: 'My name is Anas, and I''m currently wrapping up my CS degree at UAlberta.
      I enjoy mucking about & learning new stuff. This blog is to document some of
      those learnings & the things that I enjoyed.'
    Title: About
  label:
    icon: /favicon.png
    iconHeight: 35
    text: Home
  showtoc: false
  socialIcons:
    - name: github
      url: https://github.com/amohamed11
    - name: linkedin
      url: https://www.linkedin.com/in/amohamed11/
  title: 'Anas Mohamed'
  tocopen: false
theme: PaperMod
title: 'Anas Mohamed'
