baseURL = "https://amohamed.io"
languageCode = "en-us"
title = "Anas Mohamed"
theme = "cactus"
copyright = "Anas Mohamed" # cactus will use title if copyright is not set

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archive"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Resume"
url = "https://raw.githubusercontent.com/amohamed11/amohamed.io/resume/Resume.pdf"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  logo = "favicon.png"
  favicon = "favicon.ico"

  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false

  # Home page settings
  description = "My name is Anas, and I recently finished wrapping up my CS degree at UAlberta. I enjoy mucking about & learning new stuff. This blog is to document some of those learnings & other things that I find interesting."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 4 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/amohamed11" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/amohamed11"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/amohamed11/"
